# Generated by Django 5.2.4 on 2025-08-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('channel', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('url', models.URLField()),
                ('playlist_name', models.CharField(max_length=200)),
            ],
        ),
    ]
